### ISSUE TITLE
Module does not load

### ISSUE THREAD

**Issue by skiracerdude** [modpluz/xbilling#6]
Module produces blank page when opened. 

Using Sentora 1.0.0.

**Comment by skiracerdude** [comment]
Fixed using this solution found on the forum post:

Solution : 
In this file : 
/etc/sentora/panel/modules/xbilling/code/controller.ext.php

change this line : 
   static $module_db = 'zpanel_xbilling';
to : 
   static $module_db = 'sentora_xbilling';

================UP================
change only server_app from 
$server_app = 'zpanel';
to : 
$server_app = 'sentora';
================UP================

**Comment by modpluz** [comment]
Hard coding these variables is not advisable as it defeats the purpose of compatibility between the two softwares.

The module has been updated to fix the issue addressed above.
